name: nagios
version: 4.4.9
summary: Nagios is a host/service/network monitoring program.
description: |
  Nagios is a host/service/network monitoring program written in C and released under the GNU General Public License, version 2. 
  CGI programs are included to allow you to view the current status, history, etc via a web interface if you so desire.
  Visit the Nagios homepage at https://www.nagios.org for documentation, new releases, bug reports, information on discussion forums, and more.

confinement: devmode
grade: stable
base: core20

apps:
  nagios-core:
    command: usr/local/nagios/bin/nagios
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  
  verifyconfig:
    command: usr/local/nagios/bin/nagios -v usr/local/nagios/etc/nagios.cfg


parts:
  nagios-core:
    source: https://github.com/NagiosEnterprises/nagioscore.git
    source-branch: nagios-4.4.9
    plugin: autotools
    override-build: |
        ./configure --with-httpd-conf=/etc/apache2/sites-enabled
        make all
        make install-groups-users
        usermod -a -G nagios www-data
        make install-daemoninit
        make install-commandmode
        make install-config
        make install-webconf
        a2enmod cgi
        a2enmod rewrite
        htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin
        systemctl restart apache2.service
    build-packages: [autoconf, gcc, libc6, make, wget, unzip, apache2, php, libapache2-mod-php7.4, libgd-dev]
    stage-packages: [wget, unzip, apache2, php, libapache2-mod-php7.4, libgd-dev]
    
  nagios-plugins:
    after:
      - nagios-core
    source: https://github.com/nagios-plugins/nagios-plugins.git
    source-branch: release-2.4.2 
    plugin: autotools
    override-build: |
        ./tools/setup
        snapcraftctl build
    build-packages:
      - autoconf
      - gcc
      - libc6
      - libmcrypt-dev
      - make
      - libssl-dev
      - wget
      - bc
      - gawk
      - dc
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - libdbi-dev
      - libldap2-dev
      - libmysqlclient-dev
      - dnsutils
      - smbclient
      - qstat
      - fping
      
    stage-packages:
      - libmcrypt-dev
      - libssl-dev
      - wget
      - bc
      - gawk
      - dc
      - snmp
      - libnet-snmp-perl
      - gettext
      - libdbi-dev
      - libldap2-dev
      - libmysqlclient-dev
      - dnsutils
      - smbclient
      - qstat
      - fping

layout:
  usr/local/nagios:
    bind: $SNAP_COMMON/usr/local/nagios
